### ISSUE TITLE
Attempting with esp8266

### ISSUE THREAD

**Issue by augisbud** [smartinick/esp32_xiaomi_m365#1]
Hello, I have a fake wemos oled board for the esp8266, however it cannot compile bc esp32 has more pins then esp8266, any ideas?

**Comment by smartinick** [comment]
it does not depend on the pins.
right now it does not compile with esp8266, it did before, but i never testet the one-wire-uart on esp8266, then i kept devloping on esp32 and therefore there are many compile errors now on esp8266.
but i just started with testing on esp8266, so please wait for the next commit

**Comment by smartinick** [comment]
Just compiled on esp8266, connected to display and scooter.... it's working...
