### ISSUE TITLE
Turn front/rear light on/off using data bus

### ISSUE THREAD

**Issue by S-m-i-t-h** [smartinick/esp32_xiaomi_m365#10]
I would like to know it it is possible to turn lights on/off using data bus.

Thanks in advance

**Comment by S-m-i-t-h** [comment]
Nice to read that. Please, don't forget the 8.5"/10" wheel configuration. 
Very good job!

**Comment by smartinick** [comment]
No, i'll also add a beep-when-driving-backward just for fun with the people at the supermarket queue ;)

**Comment by S-m-i-t-h** [comment]
LOL, that will be very usefull!
