### ISSUE TITLE
turn off scooter?

### ISSUE THREAD

**Issue by juergengunz** [smartinick/esp32_xiaomi_m365#19]
is it possible to turn of the scooter or prevent user from turning it on by pressing the power button?

**Comment by smartinick** [comment]
we can lock it ,so it's on and can't be turned off.
or we can turn it off.
but we can not prevent the user from turning it on.
we could turn it off asap it is turned on. but how do we exit that mode?
(remember - we have no power when the scooter is turned off, so the esp is
also turned off).

and what's the idea behind it?

**Comment by juergengunz** [comment]
we are building a module that allows the user to rent the scooter, and we don't want people to ride with it, when they did not rent it.

we could power the esp by connecting it to the scooter battery

**Comment by juergengunz** [comment]
what about battery consumption? don't you think that drains the battery too much?

another question. do you know if the data connection is the same with scooter from Segway Ninebot ES1 & ES2? I mean they a pretty similar?

**Comment by juergengunz** [comment]
What if they reset the scooter ?

smartinick <notifications@github.com> schrieb am Mi. 17. Okt. 2018 um 16:20:

**Comment by smartinick** [comment]
> what about battery consumption? don't you think that drains the battery too much?
test it.... :D
it all depends on your concept for renting - do your customers have to return the scooter to some "base station" or is it like bird - they start/stop the rent "anywhere"...?you'll have to charge them anyways... depending on your business modell the battery use might be an issue or not.... how much will it drain the battery in locked mode per hour/day? i have no idea.... test it... 🗡 

you could also remove the power-button, have your own module "always on" and turn on/off the scooter from your module.
 
> another question. do you know if the data connection is the same with scooter from Segway Ninebot ES1 & ES2? I mean they a pretty similar?
i don't have those, so i don't know it. as it's sort of the same company i'd guess it's very similar.

**Comment by smartinick** [comment]
> What if they reset the scooter ? smartinick <notifications@github.com> schrieb am Mi. 17. Okt. 2018 
if you mean reset in locked mode? that's not possible... there's only 3 ways to turn it off from locked mode, all of them need either a lot of time (and a charger) or access to the databus of the scooter or to the main battery.
