### ISSUE TITLE
wireless version

### ISSUE THREAD

**Issue by plywak1896** [smartinick/esp32_xiaomi_m365#22]
Hello, do you have wireless code version? BLE + ESP32 + external battery?

**Comment by smartinick** [comment]
Nope. Never needed that/saw a sense in it.
but it's not many lines of code for the ble connection, but to make it properly the m365client should be split into a serial-communication subclass (uart/ble) and the m365 specific part. so in the end it's quite some work to integrate seamless with the current codebase.

**Comment by smartinick** [comment]
and by the way - this project moved to gitlab - closing here :D
