### ISSUE TITLE
3D model for OLED adapter

### ISSUE THREAD

**Issue by thomasDOTde** [smartinick/esp32_xiaomi_m365#3]
Hey,

do you have the model of the 3D printed model of this video available and might want to add it?
https://www.youtube.com/watch?v=0CWng6unzn4&t=46s

Thanks
Thomas

**Comment by smartinick** [comment]
You are mixing something here.... this project is based on a esp32, the one you refer in the video uses a atmega8.
with that information it might not be a surprise - no, i do not have the files, and i do not want to add them :)

But you could ask here: https://github.com/fogbox/m365_display, which is the repository for the version in the video :D
