### ISSUE TITLE
Share Connection Diagram

### ISSUE THREAD

**Issue by xinux87** [smartinick/esp32_xiaomi_m365#4]
Can you share the connection diagram? 
Thanks and awesome work!!

**Comment by augisbud** [comment]
![68747470733a2f2f656c656374726f2e636c75622f646174612f666f72756d2f6d657373616765732f34323633312f696d616765732f31313636302d313238302e6a7067](https://user-images.githubusercontent.com/20900574/43461202-8fd064f4-94db-11e8-9bf6-fed7c516e4d1.jpg)
This one is using Arduino Pro Mini, however it's similar to esp32/esp8266

**Comment by smartinick** [comment]
Correct, connection Diagram is the same. you could add a 680R resistor between RXI and the rest, so the current will be limited on the rx pin and therefore the gpio pin will not burn if there's any vcc problems, spikes,...

i'll "release" my schematics once i received and testet the PCBs i ordered - currently i'm waiting...

**Comment by saschaludwig** [comment]
@xinux87 
I had problems with the above wiring. The RX/TX Pins on the ESP8266 are not used but the GPIO13/15 is used.

You can also look that up in the sourcecode:
//UART0 will be remapped to GPIO 13(RX) / 15 (TX) and used for M365 Communication

When I add 680R between Scooter Data and RXI, the TX communication did not work.

Another odd thing I observed: The OLED on ESP8266 only starts when the Scooter Data Pin is not connected.
When reconnecting the Data Pin while the ESP8266 is running, RX/TX works and the display will get updates and actual values.
When starting the Scooter with Data Pin connected, the OLED does not get initialized and also no communication between ESP/Scooter is happening.
Leaves me a bit puzzled.

**Comment by smartinick** [comment]
Hi Sascha!

xinux uses a esp32, there we can define (nearly) any pins as it has a pin/switchmatrix built in. on the esp8266 the entire uart-hardware is different and it's bound to specific pins, so we have to use gpio 13/15 (unless you use a "blank" esp12 where the uart0 is not connected to a USB converter as on most dev-boards (and i've only been testing it on a dev board.

on esp32 i'm using 1kR in front of the RX pin and it works.

and for the problem with display/not initializing if m365bus is connected - thanks for the observation, you are correct!

as i'm developing on esp32 and do not plan to use as esp12, i only did a quick test and it looks like i missed this bug :D

**Comment by smartinick** [comment]
and by the way.... here's my schematics for the connection:
![image](https://user-images.githubusercontent.com/3613703/43512202-b8da9dfc-957a-11e8-8a3d-8773a54d8b28.png)

**Comment by saschaludwig** [comment]
Thanks for your answer and the hints. I have no problem with using an ESP32, I just had none available at the very beginning of my journey so I tried with the ESP8266. Generally I like the ESP32 because of the BTLE features it has. Can you give me a hint where the initialisation problem on the ESP8266 is so I can fix it?

**Comment by smartinick** [comment]
same for me, i have no idea as of now.... there's no collision between the pins (i2c and uart/swap/gpio remapping.... i had some quick ideas and testet them, didn't fix it. so i opened an issue... lets see when there's time to find out... as you are using esp32 as well it's low prio :D

for BLE i have a  sketch displaying navigation arrows/distance/streetname from komoot (android navigation), but komoot is c??p, so i have no prio to include that.

but i'm looking into other apps like locus or maybe to "grab" the infos from android-noticiation area when using google maps.

but that's a different story :D
