### ISSUE TITLE
esp8266 oled init hangs when uart connected

### ISSUE THREAD

**Issue by smartinick** [smartinick/esp32_xiaomi_m365#7]
#4 Another odd thing I observed: The OLED on ESP8266 only starts when the Scooter Data Pin is not connected.
When reconnecting the Data Pin while the ESP8266 is running, RX/TX works and the display will get updates and actual values.
When starting the Scooter with Data Pin connected, the OLED does not get initialized and also no communication between ESP/Scooter is happening.
Leaves me a bit puzzled.

**Comment by AntoineWaes** [comment]
I have the same issue .. did you manage to fix it ?

**Comment by smartinick** [comment]
nope no time so far to poke around :(

**Comment by smartinick** [comment]
dropped esp8266 support
