### ISSUE TITLE
ESP32 single initial screen in loop

### ISSUE THREAD

**Issue by Pi3t** [smartinick/esp32_xiaomi_m365#8]
Hello, I have programmed your code in an esp32 and I only get the initial screen with the drawing and after a few seconds it restarts, you could help me, thank you in advance and congratulations for your great work. a greeting

ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:952
load:0x40078000,len:6084
load:0x40080000,len:7936
entry 0x40080310
18.07.29
CDD1F1
### Searching for known wlan

Brownout detector was triggered

I fix this with:

#include "soc/soc.h"
#include "soc/rtc_cntl_reg.h"
void setup(){
WRITE_PERI_REG(RTC_CNTL_BROWN_OUT_REG, 0); //disable brownout detector

but now i only get no data screen and connection is good with 1k for rx and diode and 130R for tx, please help me, thanks in advance. a greeting.

**Comment by smartinick** [comment]
well brownout means there's a tooo low Vcc, and disabling the brownout detector will not solve that problem.
so there's some problem with your gnd/5v/3.3v cabling/voltage regulators... is gnd wired tom365 gnd?
enable the brownout detector and solve the problem... :D
is 5v wired to m365 5v? how do you create the 3.3v? can the 3.3v voltage regulator provide at least 300-350mA?
do you have the typical capacitors in front/behind the voltage regulators, the typical 100nF at the esp32 gnd/vcc pins..?

**Comment by smartinick** [comment]
closed due to no feedback
